version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: clean-code-nodejs-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-code-nodejs-api/dist
      - ./package.json:/usr/src/clean-code-nodejs-api/package.json
    ports:
      - "4000:4000"
      - "9222:9222"
    links:
      - mongo
